services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: art_studio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/art_studio_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    # Use the path to your frontend folder (sibling to backend)
    build: ../frontend 
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
